CREATE TYPE LAUNCH_TYPE_ENUM AS ENUM ('AUTOMATION', 'AGENTIC');

ALTER TABLE launch
    ADD COLUMN IF NOT EXISTS launch_type LAUNCH_TYPE_ENUM;

ALTER TABLE launch
    ALTER COLUMN launch_type SET DEFAULT 'AUTOMATION';

UPDATE launch
SET launch_type = 'AUTOMATION'
WHERE launch_type IS NULL;

ALTER TABLE launch
    ALTER COLUMN launch_type SET NOT NULL;
