UPDATE project_user SET project_role = 'MEMBER'
WHERE project_role IN ('CUSTOMER','OPERATOR');


CREATE TYPE PROJECT_ROLE_ENUM_NEW AS ENUM ('MEMBER', 'PROJECT_MANAGER');

ALTER TABLE project_user
ALTER COLUMN project_role TYPE PROJECT_ROLE_ENUM_NEW
USING (project_role::text::project_role_enum_new);

DROP TYPE PROJECT_ROLE_ENUM CASCADE;

ALTER TYPE PROJECT_ROLE_ENUM_NEW RENAME TO PROJECT_ROLE_ENUM;
